apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "hands-backstage"
  description: "hands-backstage"
  annotations:
    github.com/project-slug: shankar1414k/hands-backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: "backstage"
